DROP TABLE IF EXISTS trips CASCADE;
DROP TYPE IF EXISTS trip_status CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS delay_checks CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS delay_reports CASCADE;
